### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by lapo-luchini** [gvmwz/vmfsSparsePunchZero#4]
The original `vmkfstools -K / --punchzero` effectively keeps the original file in place, punching zeroes in the existing file with no need to make a copy.
This tools seems to create an (optimized) copy that is not sparse as a file on disk, but only sparse in the internal mapping.
This is different from `--punchzero` and can be more either useful (as it can be executed on a live host, if it's not the last snapshot) or less useful (if you lack the space for a second copy, where punching holes would work and creating a copy doesn't)… maybe it should be renamed to a name that is more relevant to the behavior, like `vmfsOptimize` or something?

**Comment by gvmwz** [comment]
The purpose of this tool is to deal with snapshots, a feature missing in vmkfstools .
As far as I know all snapshot is sparse in the internal mapping, so it's hard to optimize snapshot without creating a new one, and it's dangerous to modify file in-place.
If you don't have enough storage, you can copy vmdk file to any linux host with enough storage, shrink snapshot on that host, and copy the resulting files back to ESXi host.
